### ISSUE TITLE
docker-compose setup

### ISSUE THREAD

**Issue by jordy25519** [cennznet/state-oracle-relayer#19]
would be good to have a docker-compose setup for each local testing with an oracle

**Comment by ken-futureverse** [comment]
solved in #20

**Comment by ken-futureverse** [comment]
```
version: '3.3'
services:
  cennznet:
    image: cennznet/cennznet:2.2.0-rc6
    volumes:
      - ./.cennznet/data:/mnt/data
    command:
      - --dev
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --base-path=/mnt/data
    ports:
      - "9933:9933"
      - '9944:9944'
  relayer:
    image: cennznet/state-oracle-relayer:latest
    depends_on:
      - cennznet
    environment:
      - CENNZNET_NETWORK=ws://cennznet:9944
      - ETHEREUM_NETWORK=ropsten
```
